all: waa_bot waa_bot.service
.PHONY: all waa_bot install uninstall
lib_dir=/usr/local/lib/waa_bot
conf_dir=/usr/local/etc/waa_bot
service_dir=/etc/systemd/system
venv=${lib_dir}/venv

install: $(service_dir) waa_bot.service
	@echo Installing the service files...
	cp waa_bot.service $(service_dir)
	chown root:root $(service_dir)/waa_bot.service
	chmod 644 $(service_dir)/	.service

	@echo Installing library files...
	mkdir -p $(lib_dir)
	cp waa_bot.py $(lib_dir)
	chown root:root $(lib_dir)/*
	chmod 644 $(lib_dir)

	@echo Installing configuration files...
	mkdir -p $(conf_dir)
	cp waa_bot.env $(conf_dir)
	chown root:root $(conf_dir)/*
	chmod 644 $(conf_dir)

	@echo Creating python virtual environment and installing packages...
	python3 -m venv $(venv)
	$(venv)/bin/pip3 install -r requirements.txt

	@echo Installation complete...
	@echo run 'systemctl start waa_bot' to start service
	@echo run 'systemctl status waa_bot' to view status

uninstall:
	-systemctl stop waa_bot
	-systemctl disable waa_bot
	-rm -r $(lib_dir)
	-rm -r $(conf_dir)
	-rm -r $(service_dir)/waa_bot.service